language: node_js
node_js:
  - "7"
branches:
  only:
<<<<<<< HEAD
  - master
=======
  - webpack2
>>>>>>> webpack2
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
<<<<<<< HEAD
  - npm run build
=======
  - npm run build
>>>>>>> webpack2
